### ISSUE TITLE
Building with stack in ubuntu 18.04 seems to do nothing

### ISSUE THREAD

**Issue by fernando-alegre** [isovector/suavemente#2]
I cloned the repository from Github. Then I did `stack build`, and then I tried to run it using `./.stack-work/install/x86_64-linux/lts-12.7/8.4.3/bin/suavemente-exe`. The program ran, but no ouput was produced. I went to the Firefox browser and entered `http://localhost:8080` in the address bar, but still no output. I just got a fully white empty page.

I wonder if there is anything else I need to do to run the example.

**Comment by isovector** [comment]
Try `http://localhost:8080/zoom` --- I think the example binary is still from when I was messing around with arbitrary amounts of endpoints. Alternatively, pulling from master should fix this at `localhost:8080`.

**Comment by fernando-alegre** [comment]
Yes. That worked. Thanks!
